package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name="accion"
    ,catalog="sim"
)
public class Accion  implements java.io.Serializable {


     private Integer idAccion;
     private String accion;
     private Set<RolAccion> rolaccions = new HashSet<RolAccion>(0);

    public Accion() {
    }

	
    public Accion(String accion) {
        this.accion = accion;
    }
    public Accion(String accion, Set<RolAccion> rolaccions) {
       this.accion = accion;
       this.rolaccions = rolaccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAccion", unique=true, nullable=false)
    public Integer getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(Integer idAccion) {
        this.idAccion = idAccion;
    }
    
    @Column(name="Accion", nullable=false, length=30)
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="accion")
    public Set<RolAccion> getRolaccions() {
        return this.rolaccions;
    }
    
    public void setRolaccions(Set<RolAccion> rolaccions) {
        this.rolaccions = rolaccions;
    }




}


