package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Administracionmedicamento generated by hbm2java
 */
@Entity
@Table(name="administracionmedicamento"
    ,catalog="sim"
)
public class AdministracionMedicamento  implements java.io.Serializable {


     private Integer idAdminMedic;
     private LibroReport libroreport;
     private Date fecha;
     private String dosis;
     private String medicamento;
     private String administracion;

    public AdministracionMedicamento() {
    }

    public AdministracionMedicamento(LibroReport libroreport, Date fecha, String dosis, String medicamento, String administracion) {
       this.libroreport = libroreport;
       this.fecha = fecha;
       this.dosis = dosis;
       this.medicamento = medicamento;
       this.administracion = administracion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAdminMedic", unique=true, nullable=false)
    public Integer getIdAdminMedic() {
        return this.idAdminMedic;
    }
    
    public void setIdAdminMedic(Integer idAdminMedic) {
        this.idAdminMedic = idAdminMedic;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(LibroReport libroreport) {
        this.libroreport = libroreport;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="Dosis", nullable=false, length=20)
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }
    
    @Column(name="Medicamento", nullable=false, length=50)
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }
    
    @Column(name="Administracion", nullable=false, length=50)
    public String getAdministracion() {
        return this.administracion;
    }
    
    public void setAdministracion(String administracion) {
        this.administracion = administracion;
    }




}


