package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerta generated by hbm2java
 */
@Entity
@Table(name="alerta"
    ,catalog="sim"
)
public class Alerta  implements java.io.Serializable {


     private Integer idAlerta;
     private LibroReport libroreport;
     private String criticidad;
     private Date fecha;
     private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);

    public Alerta() {
    }

	
    public Alerta(LibroReport libroreport, String criticidad, Date fecha) {
        this.libroreport = libroreport;
        this.criticidad = criticidad;
        this.fecha = fecha;
    }
    public Alerta(LibroReport libroreport, String criticidad, Date fecha, Set<Mensaje> mensajes) {
       this.libroreport = libroreport;
       this.criticidad = criticidad;
       this.fecha = fecha;
       this.mensajes = mensajes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAlerta", unique=true, nullable=false)
    public Integer getIdAlerta() {
        return this.idAlerta;
    }
    
    public void setIdAlerta(Integer idAlerta) {
        this.idAlerta = idAlerta;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(LibroReport libroreport) {
        this.libroreport = libroreport;
    }
    
    @Column(name="Criticidad", nullable=false, length=25)
    public String getCriticidad() {
        return this.criticidad;
    }
    
    public void setCriticidad(String criticidad) {
        this.criticidad = criticidad;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="alerta")
    public Set<Mensaje> getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set<Mensaje> mensajes) {
        this.mensajes = mensajes;
    }




}


