package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ecg generated by hbm2java
 */
@Entity
@Table(name="ECG"
    ,catalog="SIM2"
)
public class Ecg  implements java.io.Serializable {


     private Integer idEcg;
     private LibroReport libroReport;
     private String estado;
     private Date fecha;
     private String captura;
     private float ppm;

    public Ecg() {
    }

	
    public Ecg(LibroReport libroReport, String estado, Date fecha, float ppm) {
        this.libroReport = libroReport;
        this.estado = estado;
        this.fecha = fecha;
        this.ppm = ppm;
    }
    public Ecg(LibroReport libroReport, String estado, Date fecha, String captura, float ppm) {
       this.libroReport = libroReport;
       this.estado = estado;
       this.fecha = fecha;
       this.captura = captura;
       this.ppm = ppm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idECG", unique=true, nullable=false)
    public Integer getIdEcg() {
        return this.idEcg;
    }
    
    public void setIdEcg(Integer idEcg) {
        this.idEcg = idEcg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroReport() {
        return this.libroReport;
    }
    
    public void setLibroReport(LibroReport libroReport) {
        this.libroReport = libroReport;
    }

    
    @Column(name="Estado", nullable=false, length=25)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Captura", length=100)
    public String getCaptura() {
        return this.captura;
    }
    
    public void setCaptura(String captura) {
        this.captura = captura;
    }

    
    @Column(name="PPM", nullable=false, precision=12, scale=0)
    public float getPpm() {
        return this.ppm;
    }
    
    public void setPpm(float ppm) {
        this.ppm = ppm;
    }




}


