package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FreceunciaRespiratoria generated by hbm2java
 */
@Entity
@Table(name="FreceunciaRespiratoria"
    ,catalog="SIM2"
)
public class FreceunciaRespiratoria  implements java.io.Serializable {


     private int idMedicion;
     private String freceunciaRespiratoria;

    public FreceunciaRespiratoria() {
    }

    public FreceunciaRespiratoria(int idMedicion, String freceunciaRespiratoria) {
       this.idMedicion = idMedicion;
       this.freceunciaRespiratoria = freceunciaRespiratoria;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="FreceunciaRespiratoria", nullable=false, length=20)
    public String getFreceunciaRespiratoria() {
        return this.freceunciaRespiratoria;
    }
    
    public void setFreceunciaRespiratoria(String freceunciaRespiratoria) {
        this.freceunciaRespiratoria = freceunciaRespiratoria;
    }




}


