package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Freceunciarespiratoria generated by hbm2java
 */
@Entity
@Table(name="freceunciarespiratoria"
    ,catalog="sim"
)
public class FreceunciaRespiratoria  implements java.io.Serializable {


     private int idMedicion;
     private String freceunciaRespiratoria;

    public FreceunciaRespiratoria() {
    }

    public FreceunciaRespiratoria(int idMedicion, String freceunciaRespiratoria) {
       this.idMedicion = idMedicion;
       this.freceunciaRespiratoria = freceunciaRespiratoria;
    }
   
     @Id 
    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }
    
    @Column(name="FreceunciaRespiratoria", nullable=false, length=20)
    public String getFreceunciaRespiratoria() {
        return this.freceunciaRespiratoria;
    }
    
    public void setFreceunciaRespiratoria(String freceunciaRespiratoria) {
        this.freceunciaRespiratoria = freceunciaRespiratoria;
    }




}


