package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LibroReport generated by hbm2java
 */
@Entity
@Table(name="LibroReport"
    ,catalog="SIM2"
)
public class LibroReport  implements java.io.Serializable {


     private Integer idLibroReport;
     private Paciente pacienteByIdPaciente;
     private Paciente pacienteByIdPaciente_1;
     private Date fechaAlta;
     private Date fechaBaja;
     private String estado;
     private Set<AdministracionMedicamento> administracionMedicamentos = new HashSet<AdministracionMedicamento>(0);
     private Set<Alerta> alertas = new HashSet<Alerta>(0);
     private Set<Ecg> ecgs = new HashSet<Ecg>(0);
     private Set<Nota> notas = new HashSet<Nota>(0);
     private Set<Medicion> medicions = new HashSet<Medicion>(0);

    public LibroReport() {
    }

	
    public LibroReport(Paciente pacienteByIdPaciente, Paciente pacienteByIdPaciente_1, Date fechaAlta, String estado) {
        this.pacienteByIdPaciente = pacienteByIdPaciente;
        this.pacienteByIdPaciente_1 = pacienteByIdPaciente_1;
        this.fechaAlta = fechaAlta;
        this.estado = estado;
    }
    public LibroReport(Paciente pacienteByIdPaciente, Paciente pacienteByIdPaciente_1, Date fechaAlta, Date fechaBaja, String estado, Set<AdministracionMedicamento> administracionMedicamentos, Set<Alerta> alertas, Set<Ecg> ecgs, Set<Nota> notas, Set<Medicion> medicions) {
       this.pacienteByIdPaciente = pacienteByIdPaciente;
       this.pacienteByIdPaciente_1 = pacienteByIdPaciente_1;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.estado = estado;
       this.administracionMedicamentos = administracionMedicamentos;
       this.alertas = alertas;
       this.ecgs = ecgs;
       this.notas = notas;
       this.medicions = medicions;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pacienteByIdPaciente"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idLibroReport", unique=true, nullable=false)
    public Integer getIdLibroReport() {
        return this.idLibroReport;
    }
    
    public void setIdLibroReport(Integer idLibroReport) {
        this.idLibroReport = idLibroReport;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Paciente getPacienteByIdPaciente() {
        return this.pacienteByIdPaciente;
    }
    
    public void setPacienteByIdPaciente(Paciente pacienteByIdPaciente) {
        this.pacienteByIdPaciente = pacienteByIdPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPaciente", nullable=false)
    public Paciente getPacienteByIdPaciente_1() {
        return this.pacienteByIdPaciente_1;
    }
    
    public void setPacienteByIdPaciente_1(Paciente pacienteByIdPaciente_1) {
        this.pacienteByIdPaciente_1 = pacienteByIdPaciente_1;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaAlta", nullable=false, length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaBaja", length=10)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }

    
    @Column(name="Estado", nullable=false, length=20)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libroReport")
    public Set<AdministracionMedicamento> getAdministracionMedicamentos() {
        return this.administracionMedicamentos;
    }
    
    public void setAdministracionMedicamentos(Set<AdministracionMedicamento> administracionMedicamentos) {
        this.administracionMedicamentos = administracionMedicamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libroReport")
    public Set<Alerta> getAlertas() {
        return this.alertas;
    }
    
    public void setAlertas(Set<Alerta> alertas) {
        this.alertas = alertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libroReport")
    public Set<Ecg> getEcgs() {
        return this.ecgs;
    }
    
    public void setEcgs(Set<Ecg> ecgs) {
        this.ecgs = ecgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libroReport")
    public Set<Nota> getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set<Nota> notas) {
        this.notas = notas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libroReport")
    public Set<Medicion> getMedicions() {
        return this.medicions;
    }
    
    public void setMedicions(Set<Medicion> medicions) {
        this.medicions = medicions;
    }




}


