package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medicion generated by hbm2java
 */
@Entity
@Table(name="Medicion"
    ,catalog="SIM2"
)
public class Medicion  implements java.io.Serializable {


     private int idMedicion;
     private LibroReport libroReport;
     private Date fecha;
     private String descripcion;

    public Medicion() {
    }

	
    public Medicion(int idMedicion, LibroReport libroReport, Date fecha) {
        this.idMedicion = idMedicion;
        this.libroReport = libroReport;
        this.fecha = fecha;
    }
    public Medicion(int idMedicion, LibroReport libroReport, Date fecha, String descripcion) {
       this.idMedicion = idMedicion;
       this.libroReport = libroReport;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroReport() {
        return this.libroReport;
    }
    
    public void setLibroReport(LibroReport libroReport) {
        this.libroReport = libroReport;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


