package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medicion generated by hbm2java
 */
@Entity
@Table(name="medicion"
    ,catalog="sim"
)
public class Medicion  implements java.io.Serializable {


     private int idMedicion;
     private LibroReport libroreport;
     private Date fecha;
     private String descripcion;

    public Medicion() {
    }

	
    public Medicion(int idMedicion, LibroReport libroreport, Date fecha) {
        this.idMedicion = idMedicion;
        this.libroreport = libroreport;
        this.fecha = fecha;
    }
    public Medicion(int idMedicion, LibroReport libroreport, Date fecha, String descripcion) {
       this.idMedicion = idMedicion;
       this.libroreport = libroreport;
       this.fecha = fecha;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(LibroReport libroreport) {
        this.libroreport = libroreport;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="Descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


