package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nivelglucosa generated by hbm2java
 */
@Entity
@Table(name="nivelglucosa"
    ,catalog="sim"
)
public class NivelGlucosa  implements java.io.Serializable {


     private int idMedicion;
     private String glucosa;
     private String dosis;

    public NivelGlucosa() {
    }

    public NivelGlucosa(int idMedicion, String glucosa, String dosis) {
       this.idMedicion = idMedicion;
       this.glucosa = glucosa;
       this.dosis = dosis;
    }
   
     @Id 
    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }
    
    @Column(name="Glucosa", nullable=false, length=20)
    public String getGlucosa() {
        return this.glucosa;
    }
    
    public void setGlucosa(String glucosa) {
        this.glucosa = glucosa;
    }
    
    @Column(name="Dosis", nullable=false, length=20)
    public String getDosis() {
        return this.dosis;
    }
    
    public void setDosis(String dosis) {
        this.dosis = dosis;
    }




}


