package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name="Nota"
    ,catalog="SIM2"
)
public class Nota  implements java.io.Serializable {


     private Integer idNota;
     private LibroReport libroReport;
     private Date fecha;
     private String texto;
     private String adjunto;

    public Nota() {
    }

	
    public Nota(LibroReport libroReport, Date fecha, String texto) {
        this.libroReport = libroReport;
        this.fecha = fecha;
        this.texto = texto;
    }
    public Nota(LibroReport libroReport, Date fecha, String texto, String adjunto) {
       this.libroReport = libroReport;
       this.fecha = fecha;
       this.texto = texto;
       this.adjunto = adjunto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idNota", unique=true, nullable=false)
    public Integer getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroReport() {
        return this.libroReport;
    }
    
    public void setLibroReport(LibroReport libroReport) {
        this.libroReport = libroReport;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="Texto", nullable=false, length=500)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }

    
    @Column(name="Adjunto", length=100)
    public String getAdjunto() {
        return this.adjunto;
    }
    
    public void setAdjunto(String adjunto) {
        this.adjunto = adjunto;
    }




}


