package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name="nota"
    ,catalog="sim"
)
public class Nota  implements java.io.Serializable {


     private Integer idNota;
     private LibroReport libroreport;
     private Date fecha;
     private String texto;
     private String adjunto;

    public Nota() {
    }

	
    public Nota(LibroReport libroreport, Date fecha, String texto) {
        this.libroreport = libroreport;
        this.fecha = fecha;
        this.texto = texto;
    }
    public Nota(LibroReport libroreport, Date fecha, String texto, String adjunto) {
       this.libroreport = libroreport;
       this.fecha = fecha;
       this.texto = texto;
       this.adjunto = adjunto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idNota", unique=true, nullable=false)
    public Integer getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idLibroReport", nullable=false)
    public LibroReport getLibroreport() {
        return this.libroreport;
    }
    
    public void setLibroreport(LibroReport libroreport) {
        this.libroreport = libroreport;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="Texto", nullable=false, length=500)
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    
    @Column(name="Adjunto", length=100)
    public String getAdjunto() {
        return this.adjunto;
    }
    
    public void setAdjunto(String adjunto) {
        this.adjunto = adjunto;
    }




}


