package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="Rol"
    ,catalog="SIM2"
)
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<RolAccion> rolAccions = new HashSet<RolAccion>(0);

    public Rol() {
    }

	
    public Rol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Rol(String nombreRol, Set<Usuario> usuarios, Set<RolAccion> rolAccions) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
       this.rolAccions = rolAccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    @Column(name="NombreRol", nullable=false, length=25)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rol")
    public Set<RolAccion> getRolAccions() {
        return this.rolAccions;
    }
    
    public void setRolAccions(Set<RolAccion> rolAccions) {
        this.rolAccions = rolAccions;
    }




}


