package org.sim.services.entities;
// Generated 03/08/2015 20:25:36 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name="rol"
    ,catalog="sim"
)
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<RolAccion> rolaccions = new HashSet<RolAccion>(0);

    public Rol() {
    }

	
    public Rol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Rol(String nombreRol, Set<Usuario> usuarios, Set<RolAccion> rolaccions) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
       this.rolaccions = rolaccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    
    @Column(name="NombreRol", nullable=false, length=25)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="rol")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="rol")
    public Set<RolAccion> getRolaccions() {
        return this.rolaccions;
    }
    
    public void setRolaccions(Set<RolAccion> rolaccions) {
        this.rolaccions = rolaccions;
    }




}


