package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RolAccion generated by hbm2java
 */
@Entity
@Table(name="RolAccion"
    ,catalog="SIM2"
    , uniqueConstraints = @UniqueConstraint(columnNames={"idRol", "idAccion"}) 
)
public class RolAccion  implements java.io.Serializable {


     private Integer idRolAccion;
     private Accion accion;
     private Rol rol;

    public RolAccion() {
    }

    public RolAccion(Accion accion, Rol rol) {
       this.accion = accion;
       this.rol = rol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idRolAccion", unique=true, nullable=false)
    public Integer getIdRolAccion() {
        return this.idRolAccion;
    }
    
    public void setIdRolAccion(Integer idRolAccion) {
        this.idRolAccion = idRolAccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAccion", nullable=false)
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idRol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }




}


