package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Temperatura generated by hbm2java
 */
@Entity
@Table(name="Temperatura"
    ,catalog="SIM2"
)
public class Temperatura  implements java.io.Serializable {


     private int idMedicion;
     private float temperatura;

    public Temperatura() {
    }

    public Temperatura(int idMedicion, float temperatura) {
       this.idMedicion = idMedicion;
       this.temperatura = temperatura;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="Temperatura", nullable=false, precision=12, scale=0)
    public float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(float temperatura) {
        this.temperatura = temperatura;
    }




}


