package org.sim.services.entities;
// Generated 06/08/2015 15:00:36 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TensionArterial generated by hbm2java
 */
@Entity
@Table(name="TensionArterial"
    ,catalog="SIM2"
)
public class TensionArterial  implements java.io.Serializable {


     private int idMedicion;
     private float tensionArterial;

    public TensionArterial() {
    }

    public TensionArterial(int idMedicion, float tensionArterial) {
       this.idMedicion = idMedicion;
       this.tensionArterial = tensionArterial;
    }
   
     @Id 

    
    @Column(name="idMedicion", unique=true, nullable=false)
    public int getIdMedicion() {
        return this.idMedicion;
    }
    
    public void setIdMedicion(int idMedicion) {
        this.idMedicion = idMedicion;
    }

    
    @Column(name="TensionArterial", nullable=false, precision=12, scale=0)
    public float getTensionArterial() {
        return this.tensionArterial;
    }
    
    public void setTensionArterial(float tensionArterial) {
        this.tensionArterial = tensionArterial;
    }




}


